# Generated by Django 5.1.3 on 2024-11-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='action',
            field=models.CharField(max_length=512),
        ),
    ]
